/**
 * Bundled gift art, keyed by slug. Metro needs static require() paths, so this is one line per
 * asset (assets/gifts/<slug>.png). The five placeholder slots have no file and no entry: they use
 * the glyph tile system (GiftIcon).
 */
import type { ImageSourcePropType } from 'react-native';

export const GIFT_ICONS: Record<string, ImageSourcePropType> = {
  action: require('../../../assets/gifts/action.png'),
  avocado: require('../../../assets/gifts/avocado.png'),
  'balloon-bundle': require('../../../assets/gifts/balloon-bundle.png'),
  'big-wave': require('../../../assets/gifts/big-wave.png'),
  'birthday-cake': require('../../../assets/gifts/birthday-cake.png'),
  'book-stack': require('../../../assets/gifts/book-stack.png'),
  bouquet: require('../../../assets/gifts/bouquet.png'),
  'bright-idea': require('../../../assets/gifts/bright-idea.png'),
  'cactus-hug': require('../../../assets/gifts/cactus-hug.png'),
  campfire: require('../../../assets/gifts/campfire.png'),
  campout: require('../../../assets/gifts/campout.png'),
  cherries: require('../../../assets/gifts/cherries.png'),
  cupcake: require('../../../assets/gifts/cupcake.png'),
  daisy: require('../../../assets/gifts/daisy.png'),
  'disco-ball': require('../../../assets/gifts/disco-ball.png'),
  fireworks: require('../../../assets/gifts/fireworks.png'),
  'forest-walk': require('../../../assets/gifts/forest-walk.png'),
  'good-morning': require('../../../assets/gifts/good-morning.png'),
  goodnight: require('../../../assets/gifts/goodnight.png'),
  headphones: require('../../../assets/gifts/headphones.png'),
  'heart-shades': require('../../../assets/gifts/heart-shades.png'),
  heart: require('../../../assets/gifts/heart.png'),
  'hype-horn': require('../../../assets/gifts/hype-horn.png'),
  'island-day': require('../../../assets/gifts/island-day.png'),
  'just-peachy': require('../../../assets/gifts/just-peachy.png'),
  'lemon-drop': require('../../../assets/gifts/lemon-drop.png'),
  'little-gift': require('../../../assets/gifts/little-gift.png'),
  'love-letter': require('../../../assets/gifts/love-letter.png'),
  'lucky-clover': require('../../../assets/gifts/lucky-clover.png'),
  'main-stage': require('../../../assets/gifts/main-stage.png'),
  'mountain-top': require('../../../assets/gifts/mountain-top.png'),
  'palm-tree': require('../../../assets/gifts/palm-tree.png'),
  'paper-plane': require('../../../assets/gifts/paper-plane.png'),
  'party-popper': require('../../../assets/gifts/party-popper.png'),
  pencil: require('../../../assets/gifts/pencil.png'),
  'player-two': require('../../../assets/gifts/player-two.png'),
  'playlist-for-you': require('../../../assets/gifts/playlist-for-you.png'),
  polaroid: require('../../../assets/gifts/polaroid.png'),
  popcorn: require('../../../assets/gifts/popcorn.png'),
  rainbow: require('../../../assets/gifts/rainbow.png'),
  seashell: require('../../../assets/gifts/seashell.png'),
  smile: require('../../../assets/gifts/smile.png'),
  snapshot: require('../../../assets/gifts/snapshot.png'),
  sparkle: require('../../../assets/gifts/sparkle.png'),
  starfish: require('../../../assets/gifts/starfish.png'),
  'story-time': require('../../../assets/gifts/story-time.png'),
  strawberry: require('../../../assets/gifts/strawberry.png'),
  sunrise: require('../../../assets/gifts/sunrise.png'),
  'treasure-map': require('../../../assets/gifts/treasure-map.png'),
  'true-north': require('../../../assets/gifts/true-north.png'),
  tulip: require('../../../assets/gifts/tulip.png'),
  'warm-mug': require('../../../assets/gifts/warm-mug.png'),
  'watermelon-slice': require('../../../assets/gifts/watermelon-slice.png'),
  'whole-world': require('../../../assets/gifts/whole-world.png'),
  'youre-a-star': require('../../../assets/gifts/youre-a-star.png'),
};
